/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controlador.Controlador;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import static java.util.Objects.equals;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.domain.*;

/**
 *
 * @author rodri
 */
public class VentanaPasajeros extends javax.swing.JFrame {

    private final Controlador controlador;
    private final JFrame previo;

    /**
     * Creates new form VentanaPasajeros
     *
     * @param c : controlador
     * @param p : previo JFrame
     */
    public VentanaPasajeros(Controlador c, JFrame p) {
        this.controlador = c;
        this.previo = p;
        initComponents();
        //limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPasajerosItinerario = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPasajero = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnDatosPasajero_Eliminar = new javax.swing.JButton();
        btnDatosPasajero_Limpiar = new javax.swing.JButton();
        btnDatosPasajero_Guardar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        dpFechaNac = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        rbPastaCarne = new javax.swing.JRadioButton();
        rbPastaSalsa = new javax.swing.JRadioButton();
        rbCarneEnsalada = new javax.swing.JRadioButton();
        rbEnsalada = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtTarifa = new javax.swing.JTextField();
        AsientoFila = new javax.swing.JSpinner();
        AsientoColumna = new javax.swing.JSpinner();
        btnReservarAsiento_Eliminar = new javax.swing.JButton();
        btnReservarAsiento_Limpiar = new javax.swing.JButton();
        btnReservarAsiento_Guardar = new javax.swing.JButton();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        btnBuscarAsiento = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblPasajero = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pasajeros");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("idPasajero");

        tbPasajerosItinerario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idReserva", "Fecha", "Origen", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbPasajerosItinerario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPasajerosItinerarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPasajerosItinerario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("idPasajero");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Email");

        txtIdPasajero.setEditable(false);

        btnDatosPasajero_Eliminar.setText("Eliminar");
        btnDatosPasajero_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPasajero_EliminarActionPerformed(evt);
            }
        });

        btnDatosPasajero_Limpiar.setText("Limpiar");
        btnDatosPasajero_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPasajero_LimpiarActionPerformed(evt);
            }
        });

        btnDatosPasajero_Guardar.setText("Guardar");
        btnDatosPasajero_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosPasajero_GuardarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel15.setText("F. Nacim");

        jLabel17.setText("PREFERENCIAS COMIDA");

        buttonGroup1.add(rbPastaCarne);
        rbPastaCarne.setText("Pasta + Carne");

        buttonGroup1.add(rbPastaSalsa);
        rbPastaSalsa.setText("Pasta + Salsa");

        buttonGroup1.add(rbCarneEnsalada);
        rbCarneEnsalada.setText("Carne + Ensalada");

        buttonGroup1.add(rbEnsalada);
        rbEnsalada.setText("Ensalada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbPastaSalsa)
                            .addComponent(jLabel17)
                            .addComponent(rbPastaCarne))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbEnsalada)
                            .addComponent(rbCarneEnsalada)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPasajero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDatosPasajero_Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatosPasajero_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatosPasajero_Guardar)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDatosPasajero_Eliminar, btnDatosPasajero_Guardar, btnDatosPasajero_Limpiar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dpFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbPastaCarne)
                        .addGap(18, 18, 18)
                        .addComponent(rbPastaSalsa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCarneEnsalada)
                        .addGap(18, 18, 18)
                        .addComponent(rbEnsalada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatosPasajero_Limpiar)
                    .addComponent(btnDatosPasajero_Guardar)
                    .addComponent(btnDatosPasajero_Eliminar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("DatosPasajero", jPanel1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/737-800-nac.jpg"))); // NOI18N

        jLabel9.setText("ORIGEN");

        jLabel10.setText("DESTINO");

        jLabel11.setText("FECHA");

        jLabel12.setText("TARIFA");

        jLabel13.setText("ASIENTO");

        txtTarifa.setEditable(false);

        AsientoFila.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33"}));

        AsientoColumna.setModel(new javax.swing.SpinnerListModel(new String[] {"A", "B", "C", "D", "E", "F"}));

        btnReservarAsiento_Eliminar.setText("Eliminar");
        btnReservarAsiento_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarAsiento_EliminarActionPerformed(evt);
            }
        });

        btnReservarAsiento_Limpiar.setText("Limpiar");
        btnReservarAsiento_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarAsiento_LimpiarActionPerformed(evt);
            }
        });

        btnReservarAsiento_Guardar.setText("Guardar");
        btnReservarAsiento_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarAsiento_GuardarActionPerformed(evt);
            }
        });

        btnBuscarAsiento.setText("Buscar");
        btnBuscarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(AsientoFila, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AsientoColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dpFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(txtDestino)
                                    .addComponent(txtOrigen)
                                    .addComponent(txtTarifa))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReservarAsiento_Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReservarAsiento_Limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnReservarAsiento_Guardar)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarAsiento)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReservarAsiento_Eliminar, btnReservarAsiento_Guardar, btnReservarAsiento_Limpiar});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(AsientoFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AsientoColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBuscarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservarAsiento_Limpiar)
                    .addComponent(btnReservarAsiento_Guardar)
                    .addComponent(btnReservarAsiento_Eliminar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ReservarAsiento", jPanel3);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("PASAJERO");

        lblPasajero.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblPasajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblPasajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (this.controlador.buscarPasajero(Long.valueOf(this.txtBuscar.getText())) != null) {
            Pasajero p = this.controlador.buscarPasajero(Long.valueOf(this.txtBuscar.getText()));
            this.txtIdPasajero.setText(p.getIdPasajero().toString());
            this.txtNombre.setText(p.getNombre());
            this.txtApellido.setText(p.getApellido());
            this.txtTelefono.setText(p.getTelefono());
            this.txtEmail.setText(p.getEmail());
            this.dpFechaNac.setDate(p.getFnac());
            this.lblPasajero.setText(p.getNombre() + " " + p.getApellido());
            if (null != p.getComida()) {
                switch (p.getComida()) {
                    case "PASTA + CARNE":
                        this.rbPastaCarne.doClick();
                        break;
                    case "CARNE + ENSALADA":
                        this.rbCarneEnsalada.doClick();
                        break;
                    case "PASTA + SALSA":
                        this.rbPastaSalsa.doClick();
                        break;
                    case "ENSALADA":
                        this.rbEnsalada.doClick();
                        break;
                    default:
                        break;
                }
            }
            poblarTablaPasajerosItinerario(p);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "No existe pasajero con este id, desea agregar uno?", "", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                limpiarPasajeros();
                this.txtNombre.requestFocus();
            } else {
                limpiarPasajeros();
                this.txtBuscar.requestFocus();
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDatosPasajero_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPasajero_GuardarActionPerformed
        String id = this.txtIdPasajero.getText();
        String comida = null;

        if (this.rbCarneEnsalada.isSelected()) {
            comida = this.rbCarneEnsalada.getText();
        } else if (this.rbEnsalada.isSelected()) {
            comida = this.rbEnsalada.getText();
        } else if (this.rbPastaCarne.isSelected()) {
            comida = this.rbPastaCarne.getText();
        } else if (this.rbPastaSalsa.isSelected()) {
            comida = this.rbPastaSalsa.getText();
        } else {
            comida = "";
        }

        if ("".equals(id)) {
            this.controlador.agregarPasajero(false, comida, this.txtNombre.getText().toUpperCase(), this.txtApellido.getText().toUpperCase(),
                    this.txtTelefono.getText().toUpperCase(), this.txtEmail.getText().toUpperCase(), this.dpFechaNac.getDate());

        } else {
            Pasajero p = this.controlador.buscarPasajero(Long.valueOf(id));
            boolean vf = false;

            if (p.getReservas().size() < 10) {
                vf = false;
            } else if (p.getReservas().size() >= 10) {
                vf = true;
            }

            this.controlador.editarPasajero(p, vf, comida, this.txtNombre.getText().toUpperCase(), this.txtApellido.getText().toUpperCase(),
                    this.txtTelefono.getText().toUpperCase(), this.txtEmail.getText().toUpperCase(), this.dpFechaNac.getDate());
        }

        limpiarPasajeros();
        this.lblPasajero.setText("");

    }//GEN-LAST:event_btnDatosPasajero_GuardarActionPerformed

    private void btnReservarAsiento_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarAsiento_GuardarActionPerformed
        String origen = this.txtOrigen.getText().toUpperCase();
        String destino = this.txtDestino.getText().toUpperCase();
        Date fecha = this.dpFecha.getDate();
        String fila = (String) this.AsientoFila.getValue();
        String columna = (String) this.AsientoColumna.getValue();

        Vuelo v = this.controlador.buscarODF(origen, destino, fecha);

        if (v == null) {
            JOptionPane.showMessageDialog(null, "Vuelo NO encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean disponible = true;
            Vuelo vu = this.controlador.buscarVuelo(v.getIdVuelo());
            List<Reserva> reservas = vu.getReservas();
            for (Reserva r : reservas) {
                if (r.getFila().equals(fila)
                        && r.getColumna().equals(columna)) {
                    disponible = false;
                    break;
                }
            }

            if (disponible == false) {
                JOptionPane.showMessageDialog(null, "Asiento NO disponible", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int precio;
                int f = Integer.valueOf(fila);
                if (f < 6 || f == 15 || f == 17) {
                    precio = v.getDistancia() * 2;
                } else {
                    precio = v.getDistancia();
                }
                if (this.txtIdPasajero.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe buscar un Pasajero", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    Pasajero p = this.controlador.buscarPasajero(Long.valueOf(this.txtIdPasajero.getText()));
                    this.controlador.agregarReserva(fila, columna, precio, v, p);
                    limpiarReservas();
                    poblarTablaPasajerosItinerario(p);
                }
            }
        }

    }//GEN-LAST:event_btnReservarAsiento_GuardarActionPerformed

    private void btnBuscarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsientoActionPerformed
        String origen = this.txtOrigen.getText().toUpperCase();
        String destino = this.txtDestino.getText().toUpperCase();
        Date fecha = this.dpFecha.getDate();
        String fila = (String) this.AsientoFila.getValue();
        String columna = (String) this.AsientoColumna.getValue();

        Vuelo v = this.controlador.buscarODF(origen, destino, fecha);

        if (v == null) {
            JOptionPane.showMessageDialog(null, "Vuelo NO encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean disponible = true;
            Vuelo vu = this.controlador.buscarVuelo(v.getIdVuelo());
            List<Reserva> reservas = vu.getReservas();
            for (Reserva r : reservas) {
                if (r.getFila().equals(fila)
                        && r.getColumna().equals(columna)) {
                    disponible = false;
                    break;
                }
            }
            if (disponible == false) {
                JOptionPane.showMessageDialog(null, "Asiento NO disponible", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int precio;
                int f = Integer.valueOf(fila);
                if (f < 6 || f == 15 || f == 17) {
                    precio = v.getDistancia() * 2;
                } else {
                    precio = v.getDistancia();
                }
                this.txtTarifa.setText(String.valueOf(precio));
                JOptionPane.showMessageDialog(null, "Asiento  disponible", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnBuscarAsientoActionPerformed

    private void btnDatosPasajero_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPasajero_EliminarActionPerformed

        String id = this.txtIdPasajero.getText();
        if ("".equals(id)) {
            JOptionPane.showMessageDialog(null, "Debe buscar un Pasajero", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Pasajero p = this.controlador.buscarPasajero(Long.valueOf(id));
            this.controlador.eliminarPasajero(p);
            JOptionPane.showMessageDialog(null, "TRIPULANTE ELIMINADO CORRECTAMENTE", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        limpiarPasajeros();
        limpiarReservas();
        this.lblPasajero.setText("");
    }//GEN-LAST:event_btnDatosPasajero_EliminarActionPerformed

    private void btnDatosPasajero_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosPasajero_LimpiarActionPerformed
        limpiarPasajeros();
        limpiarReservas();
        this.lblPasajero.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatosPasajero_LimpiarActionPerformed

    private void btnReservarAsiento_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarAsiento_LimpiarActionPerformed
        String id = this.txtIdPasajero.getText();
        if (!id.isEmpty()) {
            limpiarReservas();
            Pasajero p = this.controlador.buscarPasajero(Long.valueOf(id));
            poblarTablaPasajerosItinerario(p);
        }
    }//GEN-LAST:event_btnReservarAsiento_LimpiarActionPerformed

    private void btnReservarAsiento_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarAsiento_EliminarActionPerformed
        if (!this.tbPasajerosItinerario.getSelectionModel().isSelectionEmpty()) {
            Reserva r = this.controlador.buscarReserva((Long) this.tbPasajerosItinerario.getModel().getValueAt(this.tbPasajerosItinerario.getSelectedRow(), 0));
            this.controlador.eliminarReserva(r);
            JOptionPane.showMessageDialog(null, "TRIPULANTE ELIMINADO CORRECTAMENTE", "Error", JOptionPane.INFORMATION_MESSAGE);
            limpiarReservas();
            String id = this.txtIdPasajero.getText();
            Pasajero p = this.controlador.buscarPasajero(Long.valueOf(id));
            poblarTablaPasajerosItinerario(p);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una reserva a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnReservarAsiento_EliminarActionPerformed

    private void tbPasajerosItinerarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPasajerosItinerarioMouseClicked
        if (!this.tbPasajerosItinerario.getSelectionModel().isSelectionEmpty()) {
            Reserva r = this.controlador.buscarReserva((Long) this.tbPasajerosItinerario.getModel().getValueAt(this.tbPasajerosItinerario.getSelectedRow(), 0));
            this.txtOrigen.setText(r.getVuelo().getOrigen());
            this.txtDestino.setText(r.getVuelo().getDestino());
            this.dpFecha.setDate(r.getVuelo().getFechaSalida());
            this.txtTarifa.setText(String.valueOf(r.getPrecio()));
            this.AsientoColumna.setValue(r.getColumna());
            this.AsientoFila.setValue(r.getFila());
        }
    }//GEN-LAST:event_tbPasajerosItinerarioMouseClicked

    private void limpiarPasajeros() {
        this.txtBuscar.setText("");
        this.txtIdPasajero.setText("");
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtTelefono.setText("");
        this.txtEmail.setText("");
        this.dpFechaNac.setDate(null);
        this.buttonGroup1.clearSelection();

        DefaultTableModel dtmPI = (DefaultTableModel) this.tbPasajerosItinerario.getModel();
        dtmPI.getDataVector().removeAllElements();
        dtmPI.fireTableDataChanged();

    }

    private void limpiarReservas() {
        this.txtOrigen.setText("");
        this.txtDestino.setText("");
        this.dpFecha.setDate(null);
        this.AsientoFila.getMinimumSize();
        this.AsientoColumna.getMinimumSize();
        this.txtTarifa.setText("");

    }

    public void poblarTablaPasajerosItinerario(Pasajero p) {
        Object[] nombreColumnas = {"idReserva", "Fecha", "Origen", "Destino"};
        DefaultTableModel dtmR = new DefaultTableModel(new Object[0][0], nombreColumnas);
        List<Reserva> reservas = p.getReservas();
        System.out.println(reservas.toString());
        for (Reserva reserva : reservas) {
            Object[] t = new Object[4];
            t[0] = reserva.getIdReserva();
            t[1] = reserva.getVuelo().getFechaSalida();
            t[2] = reserva.getVuelo().getOrigen();
            t[3] = reserva.getVuelo().getDestino();
            dtmR.addRow(t);
        }
        this.tbPasajerosItinerario.setModel(dtmR);
        this.tbPasajerosItinerario.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AsientoColumna;
    private javax.swing.JSpinner AsientoFila;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarAsiento;
    private javax.swing.JButton btnDatosPasajero_Eliminar;
    private javax.swing.JButton btnDatosPasajero_Guardar;
    private javax.swing.JButton btnDatosPasajero_Limpiar;
    private javax.swing.JButton btnReservarAsiento_Eliminar;
    private javax.swing.JButton btnReservarAsiento_Guardar;
    private javax.swing.JButton btnReservarAsiento_Limpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private org.jdesktop.swingx.JXDatePicker dpFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblPasajero;
    private javax.swing.JRadioButton rbCarneEnsalada;
    private javax.swing.JRadioButton rbEnsalada;
    private javax.swing.JRadioButton rbPastaCarne;
    private javax.swing.JRadioButton rbPastaSalsa;
    private javax.swing.JTable tbPasajerosItinerario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdPasajero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
